import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ToastProvider } from "@/providers/toast-provider";

import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-200",
          inter.className
        )}
      >
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
